seed: 42

run:
  root_dir: runs

data:
  dataset_name: office_31
  root: /home/ljzhang/data/sfada/office-31
  source_domain: "amazon"
  num_classes: 31
  image_size: 224

model:
  backbone: resnet50
  pretrained: true
  bottleneck_dim: 256
  bottleneck_relu: true

train:
  source_epochs: 20
  batch_size: 64
  num_workers: 4
  log_every_iters: 13
  lr: 0.0001
  weight_decay: 0.0005
  use_scheduler: true

eval:
  batch_size: 128
  num_workers: 4
  source_ckpt: best
  monitor_source_val: true
